import { isNoteDraftDirty } from './engine.js';
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const day = value => new Date(value).toLocaleDateString(undefined,{day:'numeric',month:'short'});
const statuses = {open:'Open note',revisit:'Revisit',resolved:'Resolved note'};
export const emptyNote = sessionId => ({id:'',sessionId:sessionId||'',title:'',body:'',status:'open'});

export function notebookPage(state, sessions, {query='',filter='all',message='',storageProblem=''}={}) {
  const notes = state.notes || [];
  const draft = state.noteDraft || emptyNote();
  const current = notes.find(n=>n.id===draft.id);
  const topic = id => sessions.find(s=>s.id===id)?.title || 'General study note';
  const visible = [...notes].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).filter(n=>(filter==='all'||n.status===filter)&&`${n.title} ${n.body} ${topic(n.sessionId)}`.toLowerCase().includes(query.toLowerCase().trim()));
  return `<div class="page-top"><div><p class="page-kicker">Your working record</p><h1>Study notebook</h1><p class="intro">What clicked. What changed. What to try next.</p></div><div class="page-tools"><button class="btn" data-action="export-notebook">Export Markdown <span class="action-arrow" aria-hidden="true">↗</span></button><a href="#storage">Backup & restore</a></div></div>
  <div class="notebook-meta"><span>${notes.length} ${notes.length===1?'note':'notes'}</span><span>${notes.filter(n=>n.status==='revisit').length} marked to revisit</span><a href="#history">${state.attempts.length} recorded attempts →</a></div>
  <div class="notebook-layout"><section class="note-index" aria-label="Saved notes"><div class="section-heading"><h2>Your notes</h2><button class="text-button" data-action="new-note">+ New note</button></div>
  <form id="note-search-form" class="search-form"><label class="sr-only" for="note-search">Search notes</label><input type="search" id="note-search" name="query" value="${esc(query)}" placeholder="Search your notebook" maxlength="160"><button class="btn" type="submit">Find</button></form>
  <label class="field note-filter">Show notes<select id="note-filter"><option value="all" ${filter==='all'?'selected':''}>All notes</option>${Object.entries(statuses).map(([id,label])=>`<option value="${id}" ${filter===id?'selected':''}>${label}</option>`).join('')}</select></label>
  <p class="fine" role="status">${visible.length} ${visible.length===1?'note':'notes'} shown</p><div class="note-list">${visible.length?visible.map(n=>`<button class="note-select" data-action="edit-note" data-note-id="${esc(n.id)}" aria-pressed="${draft.id===n.id}"><span class="note-topic">${esc(topic(n.sessionId))}</span><strong>${esc(n.title)}</strong><span class="note-preview">${esc(n.body.slice(0,100))}${n.body.length>100?'…':''}</span><span class="note-stamp">${esc(statuses[n.status])} · ${day(n.updatedAt)}${n.revisions.length?' · updated':''}</span></button>`).join(''):`<div class="empty"><h3>${notes.length?'No matching notes.':'Give the next session a starting point.'}</h3><p>${notes.length?'Change the search or status filter.':'Save one insight or a question. Link it to the exercise so you can find it next time.'}</p></div>`}</div></section>
  <section class="note-paper" aria-label="Note editor"><div class="section-heading"><h2>${current?'Update your note':'Capture a study note'}</h2>${current?`<span class="fine">Updated ${day(current.updatedAt)}</span>`:'<span class="fine">Private to this browser</span>'}</div><form id="note-form">
  <div class="form-grid"><label class="field">Related session<select name="sessionId"><option value="">General study note</option>${sessions.map(s=>`<option value="${s.id}" ${draft.sessionId===s.id?'selected':''}>${esc(s.title)}</option>`).join('')}</select></label><label class="field">Note status<select name="status">${Object.entries(statuses).map(([id,label])=>`<option value="${id}" ${draft.status===id?'selected':''}>${label}</option>`).join('')}</select></label></div>
  <label class="field">Title<input name="title" type="text" maxlength="200" required placeholder="The one thing I want to remember" value="${esc(draft.title)}"></label>
  <label class="field">Your note<textarea name="body" maxlength="12000" rows="9" required placeholder="What I tried…&#10;What I learned or changed…&#10;The next question or experiment…">${esc(draft.body)}</textarea></label>
  <p class="fine" id="note-draft-status" role="status">${storageProblem?'Changes are in this tab only. Export JSON to keep your work.':isNoteDraftDirty(state)?'Working draft restored. Save to file this version.':current?'This matches your saved note. Edits will create a new version.':'Drafts save as you type. Save note to add it to your notebook.'}</p>
  <div class="actions"><button class="btn primary" type="submit">${current?'Save changes':'Save note'} <span class="action-arrow" aria-hidden="true">→</span></button>${draft.sessionId?`<button type="button" class="btn quiet" data-start="${esc(draft.sessionId)}">Return to session</button>`:''}</div>
  <p id="note-message" class="feedback" role="status">${esc(message)}</p></form>
  ${current?.revisions.length?`<details class="revision-history"><summary>Previous versions (${current.revisions.length})</summary><div class="detail-body"><p class="fine">The latest 20 previous versions are kept per note.</p>${[...current.revisions].reverse().map(r=>`<article><p class="note-stamp">${day(r.updatedAt)} · ${esc(statuses[r.status])}</p><h3>${esc(r.title)}</h3><p class="preserve-lines">${esc(r.body)}</p></article>`).join('')}</div></details>`:''}
  <p class="notebook-boundary">A resolved note closes a question. Completed practice and reviewer feedback stay in <a href="#history">Review & history</a>.</p></section></div>
  <section class="notebook-portable"><h2>Keep a copy you can open anywhere.</h2><p>Export Markdown for Obsidian or your editor. JSON in Backup & restore brings the full notebook back into Padipps. Keep your exported notes and evidence somewhere you control.</p><a href="#storage">Manage backups →</a></section>`;
}
